### ISSUE TITLE
可以参考一下这个网站，批量转存并且不需要同时打开多个窗口

### ISSUE THREAD

**Issue by netcccyun** [mengzonefire/baidupan-rapidupload#1]
可以参考一下这个网站，批量转存并且不需要同时打开多个窗口
http://wp.cccyun.cc/

**Comment by mengzonefire** [comment]
ok, 我去看看

**Comment by mengzonefire** [comment]
由于原理不同, 本工具无法像那个网站一样实现功能

另外, 那个网站是发送账号信息到服务器执行转存的, 存在账号泄露的风险

**Comment by TkzcM** [comment]
理论上来说，可以 window.open 打开窗口，把表单的 target 指向子窗口，然后循环 submit 来实现

**Comment by mengzonefire** [comment]
> 理论上来说，可以 window.open 打开窗口，把表单的 target 指向子窗口，然后循环 submit 来实现

可以, 我有空研究下
