### ISSUE TITLE
-6报错

### ISSUE THREAD

**Issue by Shinyo1** [mengzonefire/baidupan-rapidupload#11]
{"errno":-6,"path":"","request_id":56637444156067536}
更换了edge和chrome、备用接口，都不行

**Comment by mengzonefire** [comment]
请认真阅读页面上的提示: 

若转存显示 {"errno":-6,"request_id":...}:

请在此浏览器打开或刷新[度盘页面](https://pan.baidu.com/)(若未登陆请登陆)再重试

若转存显示 {"errno":-6} 或 {"errno":2,"request_id":...}:

请填写bdstoken

22.10.28 17:10 使用 edge浏览器106.0.1370.52版本, 切换到备用接口, 测试转存完全正常
![Snipaste_2022-10-28_17-17-08](https://user-images.githubusercontent.com/44224240/198551916-9da36db9-c8c6-41e0-9523-5387a7472148.png)
