### ISSUE TITLE
errno":31039

### ISSUE THREAD

**Issue by 1426645584** [mengzonefire/baidupan-rapidupload#13]
errno":31039 请问这个是什么意思啊 求解答

**Comment by mengzonefire** [comment]
把秒传的最后一段文件名里的文件后缀.zip改为.ZIP即可

等下会更新文本说明上去, 详见 [秒传脚本通知区](https://greasyfork.org/zh-CN/scripts/424574)

**Comment by 1426645584** [comment]
好的 感谢 已成功 顺带一提是rar结尾 改成大写的RAR也可以成功
