### ISSUE TITLE
请问百度网盘秒传链接转换 把秒传链接复制上去后点击转换无反应是什么原因？

### ISSUE THREAD

**Issue by 1051072042** [mengzonefire/baidupan-rapidupload#14]
请问百度网盘秒传链接转换 把秒传链接复制上去后点击转换无反应是什么原因？

**Comment by mengzonefire** [comment]
请在这个载点试一下, 旧版本的转换是有问题的:

https://mengzonefire.github.io/baidupan-rapidupload/convert.html

如果依旧转换不了请反馈下输入的秒传链接

**Comment by 1051072042** [comment]
f722458a8ff1c49b5c1f4e11c2d61f4a#289915677#40697736.zip
转化为 梦姬格式

**Comment by 1051072042** [comment]
似乎是这个秒传格式的问题，但我想把这种格式的秒传链接转为梦姬格式

**Comment by mengzonefire** [comment]
你好, f722458a8ff1c49b5c1f4e11c2d61f4a#289915677#40697736.zip

是简化版的梦姬格式, 是无法转换回去的, 简化格式目前网页工具和秒传脚本均支持转存

格式相关可以参考下 [秒传文档](https://mengzonefire.code.misakanet.cn/rapid-upload-userscript-doc/document/Info/%E7%A7%92%E4%BC%A0%E6%A0%BC%E5%BC%8F.html)

**Comment by 1051072042** [comment]
短时间批量转存一万个秒传链接难以实现，如果可以写一个本地工具就好了⌓‿⌓

**Comment by mengzonefire** [comment]
> 短时间批量转存一万个秒传链接难以实现，如果可以写一个本地工具就好了⌓‿⌓

百度的接口均有频限, 短时间批量转存一万个秒传链接会导致你的百度账号被限制

另附: 秒传转存本地工具: [BaiduPCS-Go](https://github.com/qjfoidnh/BaiduPCS-Go)

**Comment by 1051072042** [comment]
感谢大佬耐心回复，受益匪浅
