### ISSUE TITLE
错误反馈

### ISSUE THREAD

**Issue by adacheung912** [mengzonefire/baidupan-rapidupload#17]
1.61d3bc0f4b5bfd80b314bdc00d596ba9#219813410#眼光的交织  在曹雪芹与马塞尔·普鲁斯特之间_涂卫群著_zhelper-search.zip
2.errno:-6

**Comment by mengzonefire** [comment]
![209621815-30362bb1-95e4-493c-87fb-b338bf22d8af](https://user-images.githubusercontent.com/44224240/209953716-9b532a1d-88e1-4262-bcf2-dda43454b986.png)
