### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by AustenSherlock** [mengzonefire/baidupan-rapidupload#19]
4fc6d694970588e56cf024bb7ccff78c#63253812#以利为利：财政关系与地方政府行为_周飞舟_zhelper-search.pdf

**Comment by AustenSherlock** [comment]
Error code {"category":4,"ctime":1673448735,"from_type":1,"fs_id":695945608967891,"isdir":0,"md5":"9626cd82cm6d1b7b7decb2ebe55be954","mtime":1673448735,"path":"\/\u4ee5\u5229\u4e3a\u5229\uff1a\u8d22\u653f\u5173\u7cfb\u4e0e\u5730\u65b9\u653f\u5e9c\u884c\u4e3a_\u5468\u98de\u821f_zhelper-search.pdf","server_filename":"\u4ee5\u5229\u4e3a\u5229\uff1a\u8d22\u653f\u5173\u7cfb\u4e0e\u5730\u65b9\u653f\u5e9c\u884c\u4e3a_\u5468\u98de\u821f_zhelper-search.pdf","size":63253812,"errno":0,"name":"\/\u4ee5\u5229\u4e3a\u5229\uff1a\u8d22\u653f\u5173\u7cfb\u4e0e\u5730\u65b9\u653f\u5e9c\u884c\u4e3a_\u5468\u98de\u821f_zhelper-search.pdf"}

**Comment by AustenSherlock** [comment]
{"errno":-6,"path":"","request_id":254122819308094205} 有时候是这个；保存至网盘时总是显示保存失败。

**Comment by mengzonefire** [comment]
第一个"errno":0,"是保存成功

其余保存失败的errno请去看文档：

https://mengzonefire.code.misakanet.cn/rapid-upload-userscript-doc/document/FAQ/%E9%94%99%E8%AF%AF%E4%BB%A3%E7%A0%81(%E7%BD%91%E9%A1%B5%E5%B7%A5%E5%85%B7).html

**Comment by AustenSherlock** [comment]
但是直接按解析链接并转存经常保存失败是为什么呢？就是我这里转存稳定性很奇怪。辛苦了！




吴彤
***@***.***



&nbsp;






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mengzonefire/baidupan-rapidupload"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月11日(星期三) 晚上11:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mengzonefire/baidupan-rapidupload] Error (Issue #19)





 
第一个"errno":0,"是保存成功
 
其余保存失败的errno请去看文档：
 
https://mengzonefire.code.misakanet.cn/rapid-upload-userscript-doc/document/FAQ/%E9%94%99%E8%AF%AF%E4%BB%A3%E7%A0%81(%E7%BD%91%E9%A1%B5%E5%B7%A5%E5%85%B7).html

**Comment by mengzonefire** [comment]
我知道的所有内容都写在文档里了，请直接看文档

**Comment by AustenSherlock** [comment]
收到，问题已解决！




吴彤
***@***.***



&nbsp;






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mengzonefire/baidupan-rapidupload"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月11日(星期三) 晚上11:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mengzonefire/baidupan-rapidupload] Error (Issue #19)





 
我知道的所有内容都写在文档里了，请直接看文档
