### ISSUE TITLE
秒链存在排列错误

### ISSUE THREAD

**Issue by taikonglaji** [mengzonefire/baidupan-rapidupload#2]
"物恋传媒第一期 (1).jpg|4546363|3ED72811EBD07AE2788E4A8557D23AB2AACA72E3|3A1F0C493D879
![微信图片_20211228104204](https://user-images.githubusercontent.com/96756838/147522002-65240a5d-082e-4720-b416-1d4ac74da97c.png) 
B8E512FD84BC0D60486AAD646CE",                    
无效的秒链，是否存在排列错误？ 如果正确排列

**Comment by mengzonefire** [comment]
这不是度盘秒传格式, 是115秒传
这里查看此工具支持的秒传格式：https://mengzonefire.code.misakanet.cn/rapid-upload-userscript-doc/format-support/
