### ISSUE TITLE
zip文件未检测到有效的秒传链接,改手动输入后报error 1

### ISSUE THREAD

**Issue by XixuHu** [mengzonefire/baidupan-rapidupload#20]
4d6c3b6e6pd1bf1bd96372679df51e18#27632348#英皇乐理精讲（1～5级）_谭展辉编著_zhelper-search.zip

{"errno":1,"path":"","request_id":318969060922538119}

**Comment by mengzonefire** [comment]
"4d6c3b6e6pd1bf1bd96372679df51e18" 是一种加密过的md5, 网页工具暂不支持转存, 会在下个版本加入支持, 工具更新前可以先使用秒传脚本转存

**Comment by mengzonefire** [comment]
已更新1.4版本, 支持此种链接的转存了
