### ISSUE TITLE
errno":20,

### ISSUE THREAD

**Issue by xiaoshuyufu** [mengzonefire/baidupan-rapidupload#21]
您好，谢谢开发这个插件。
说明：我的网盘满了，但是报的不是10号错误。

ef1fbd529d106c11105a9af0392886b0#39f9f7da96610c94ee4816377b9058c9#12715607#我们小时候  自行车之歌,苏童著,济南：明天出版社_13657950.uvz

{"errno":20,"path":"","request_id":473446737742492136}

**Comment by mengzonefire** [comment]
是这样的，10号是常规接口的报错，但现在已经改用新接口了（备用接口，一直没去测新接口的报错，不过感谢反馈，稍后会补充到文档里
