### ISSUE TITLE
help me thankyou

### ISSUE THREAD

**Issue by whiteforlife** [mengzonefire/baidupan-rapidupload#22]
e08555c77606f2dc706b3c2c856c33f2#11862636#数学分析新讲  第1册_张筑生编著_zhelper-search.zip
{"category":6,"ctime":1675428407,"from_type":1,"fs_id":308192068093834,"isdir":0,"md5":"7725b7bb6p2e9828844f7695f9c0f1c3","mtime":1675428407,"path":"\/2022\/\u6570\u5b66\u5206\u6790\u65b0\u8bb2  \u7b2c1\u518c_\u5f20\u7b51\u751f\u7f16\u8457_zhelper-search.zip","server_filename":"\u6570\u5b66\u5206\u6790\u65b0\u8bb2  \u7b2c1\u518c_\u5f20\u7b51\u751f\u7f16\u8457_zhelper-search.zip","size":11862636,"errno":0,"name":"\/2022\/\u6570\u5b66\u5206\u6790\u65b0\u8bb2  \u7b2c1\u518c_\u5f20\u7b51\u751f\u7f16\u8457_zhelper-search.zip"}
救救萌新

**Comment by mengzonefire** [comment]
看清楚页面上的说明，"errno":0 是转存成功。
