### ISSUE TITLE
"errno":9019

### ISSUE THREAD

**Issue by Harper12138** [mengzonefire/baidupan-rapidupload#25]
47ef49fe9f642acb4b6127b4cb081d35#13654797#本雅明文选_本雅明_5879612_zhelper-search.pdf

{"errno":9019,"errmsg":"need verify","request_id":574066555973376205}

**Comment by mengzonefire** [comment]
1.5版本已修复

https://mengzonefire.code.misakanet.cn/baidupan-rapidupload

https://mengzonefire.github.io/baidupan-rapidupload
