### ISSUE TITLE
错误码9019

### ISSUE THREAD

**Issue by dream336** [mengzonefire/baidupan-rapidupload#26]
errno | 9019
errmsg | "need verify"
request_id | 574753505372661250
现在也无法生成秒传了

**Comment by gilbertqian** [comment]
i encounted this error only on today, waiting for the fix.

**Comment by mengzonefire** [comment]
1.5版本已修复

https://mengzonefire.code.misakanet.cn/baidupan-rapidupload

https://mengzonefire.github.io/baidupan-rapidupload
