### ISSUE TITLE
{"errno":9019,

### ISSUE THREAD

**Issue by CJinyi1217** [mengzonefire/baidupan-rapidupload#27]
1. 5942fea8f8cc16899e759471d24e800e#43295110#Oran猪漫画教室  从零开始学漫画  1  入门篇  完全版_Oran猪著_13218479_zhelper-search.zip
2. {"errno":9019,"errmsg":"need verify","request_id":574859094056302630}

**Comment by mengzonefire** [comment]
1.5版本已修复

https://mengzonefire.code.misakanet.cn/baidupan-rapidupload

https://mengzonefire.github.io/baidupan-rapidupload
