### ISSUE TITLE
errno:9019

### ISSUE THREAD

**Issue by hyhwhocares** [mengzonefire/baidupan-rapidupload#29]
{"errno":9019,"errmsg":"need verify","request_id":575815848101838875}

**Comment by mengzonefire** [comment]
1.5版本已修复

https://mengzonefire.code.misakanet.cn/baidupan-rapidupload

https://mengzonefire.github.io/baidupan-rapidupload

**Comment by hyhwhocares** [comment]
感谢！



发自我的&nbsp;iPad


------------------ Original ------------------
From: mengzonefire ***@***.***&gt;
Date: Thu,Mar 16,2023 2:37 PM
To: mengzonefire/baidupan-rapidupload ***@***.***&gt;
Cc: hyhwhocares ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [mengzonefire/baidupan-rapidupload] errno:9019 (Issue #29)





 
1.5版本已修复
 
https://mengzonefire.code.misakanet.cn/baidupan-rapidupload
 
https://mengzonefire.github.io/baidupan-rapidupload
