### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by littlesmallsea** [mengzonefire/baidupan-rapidupload#31]
1.
7b590d9427f114f937c231b1d1403baa#3145728000#Brkkm_sknigken.7z.001
fb16b2878fe92aa532b5620bb4d43de1#2128924570#Brkkm_sknigken.7z.002
2.
(#29

**Comment by mengzonefire** [comment]
1.5版本已修复

https://mengzonefire.code.misakanet.cn/baidupan-rapidupload

https://mengzonefire.github.io/baidupan-rapidupload

http://rapidacg.gmgard.moe
