### ISSUE TITLE
#9019 错误请看这里！

### ISSUE THREAD

**Issue by DuO555** [mengzonefire/baidupan-rapidupload#32]
8473df4c936d6a0d4bd9b8f2eb361ade#3d9026ba178c5a2b38c5ba85f49df181#12752073906#/上传/253-Marugaogaski.7z鍒犻櫎 
这个是秒传链接
未知错误(#9019)

**Comment by mengzonefire** [comment]
1.5版本已修复

https://mengzonefire.code.misakanet.cn/baidupan-rapidupload

https://mengzonefire.github.io/baidupan-rapidupload

http://rapidacg.gmgard.moe

**Comment by zzzduck** [comment]
你好，请问下载后解压码在哪里查看呢？谢谢

**Comment by mengzonefire** [comment]
> 你好，请问下载后解压码在哪里查看呢？谢谢

请去找秒传链接的发布者问，这里只是转存工具

**Comment by Lencho77** [comment]
{"errno":404,"path":"","request_id":9136277657062989606
