### ISSUE TITLE
秒传完全失效

### ISSUE THREAD

**Issue by Licialicia** [mengzonefire/baidupan-rapidupload#38]
连续一周都无法正常下载书籍了，所有的书都显示转存失败，已经按照 载点2 上的错误一一排除了，但没用，求帮助。失败界面如下：

Zlib界面：https://search.zhelper.net/?[{%22name%22:%22Ylibrary%22,%22url%22:%22https://api.ylibrary.org%22,%22type%22:%22full%22,%22sensitive%22:false,%22detail%22:true}]

秒传链接：6fb8ebb3feb93195b285cb26d8675649#30583989#国际文学人类学研究_叶舒宪主编_11772365_zhelper-search.zip

百度网盘显示：转存完毕 共1个, 失败1个!
失败文件列表(点击展开):
文件：国际文学人类学研究_叶舒宪主编_11772365_zhelper-search.zip
失败原因：未知错误(#9019)

**Comment by tkoksxp** [comment]
估计是 百度又封了接口了，我这里也没办法正常使用了

**Comment by mengzonefire** [comment]
项目已停止维护，请勿反馈。
