### ISSUE TITLE
关于秒传链接使用的两个反馈

### ISSUE THREAD

**Issue by moonstonegold** [mengzonefire/baidupan-rapidupload#4]
1.在仓库中使用时，已安装脚本，点击“秒传”无发直接转存 会跳转至网盘页面
2.通过秒传链接转存页面 进行转存，已使用chrome、edge，转存依然显示{"errno":-6,"request_id":9073614337040719920}

**Comment by mengzonefire** [comment]
1. 那个秒传按钮，必须搭配 [秒传脚本](https://greasyfork.org/zh-CN/scripts/424574) 才能使用
2. 在线工具转存出现errno":-6, 先打开一遍度盘页面再转存即可（在线工具页面上附了提示）
