### ISSUE TITLE
在火狐身份标签页下无法正常使用

### ISSUE THREAD

**Issue by SirnoChan** [mengzonefire/baidupan-rapidupload#5]
应该是适配问题，无论是生成链接还是秒传都会显示失败……

**Comment by mengzonefire** [comment]
> 应该是适配问题，无论是生成链接还是秒传都会显示失败……

是指秒传脚本么, 那个的话有人反馈过:

https://greasyfork.org/zh-CN/scripts/424574/discussions/121703

说是油猴插件的适配问题, 换暴力猴插件即可
