### ISSUE TITLE
errno:2

### ISSUE THREAD

**Issue by imba-tjd** [mengzonefire/baidupan-rapidupload#6]
看 https://www.bilibili.com/video/BV1Ra411h7XF 的评论区

我没有试过普通方式用那链接有没有效。

**Comment by mengzonefire** [comment]
> 看 https://www.bilibili.com/video/BV1Ra411h7XF 的评论区
> 
> 我没有试过普通方式用那链接有没有效。

浏览器问题, 清除下浏览器缓存 或 按页面上的提示更换兼容的浏览器

**Comment by imba-tjd** [comment]
emmm我之前用的就是FF和Chromium 86没成功，不过现在用Edge登录试了一下成功了。谢谢
