### ISSUE TITLE
ios chrome edge 百度app 修改桌面版或手机版都无法使用

### ISSUE THREAD

**Issue by hktrace** [mengzonefire/baidupan-rapidupload#9]
ios chrome edge 百度app 修改桌面版或手机版都无法使用

**Comment by mengzonefire** [comment]
> ios chrome edge 百度app 修改桌面版或手机版都无法使用

未能复现，请反馈下出现的具体问题/报错？

**Comment by hktrace** [comment]
ios最新版下chrome等浏览器点击解析链接并转存返回error:2。使用老版本手动复制bdstoken则成功转存

mengzonefire ***@***.***>于2022年9月14日 周三06:34写道：

**Comment by hktrace** [comment]
"errno":2,"request_id":...}:显示这个。老版本则不会

a boy ***@***.***>于2022年9月14日 周三12:52写道：

**Comment by mengzonefire** [comment]
已经在360浏览器手机版复现, 因为没有ios设备所以一直没对safari做测试, 最开始是在chrome下测试发现bdstoken加不加没影响, 就直接删掉了, 现已复现 {"errno":-6} 和 {"errno":2,"request_id":...} 两个报错均是因为没添加bdstoken (最初未能在所有浏览器复现, 当时判断为是浏览器兼容性问题, 现在总算破案了), 感谢反馈, 会在下版本重新添加bdstoken输入

**Comment by hktrace** [comment]
嗯嗯.好的.谢谢.

**Comment by mengzonefire** [comment]
1.0版本已修复此问题, 你可以测试一下

提供的三个载点内的两个已同步更新, 另一个需要等几天才同步
